<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class GameImageDefault {
	private $game_image_default_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'game_image_default_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'game_image_default_page_init' ) );
	}

	public function game_image_default_add_plugin_page() {
		add_menu_page(
			'Game image default', // page_title
			'Game image default', // menu_title
			'manage_options', // capability
			'game-image-default', // menu_slug
			array( $this, 'game_image_default_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			2 // position
		);
	}

	public function game_image_default_create_admin_page() {
		$this->game_image_default_options = get_option( 'game_image_default_option_name' ); ?>

		<div class="wrap">
			<h2>Game image default</h2>
			<p>Game image default</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'game_image_default_option_group' );
					do_settings_sections( 'game-image-default-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function game_image_default_page_init() {
		register_setting(
			'game_image_default_option_group', // option_group
			'game_image_default_option_name', // option_name
			array( $this, 'game_image_default_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'game_image_default_setting_section', // id
			'Settings', // title
			array( $this, 'game_image_default_section_info' ), // callback
			'game-image-default-admin' // page
		);

		add_settings_field(
			'image_0', // id
			'image', // title
			array( $this, 'image_0_callback' ), // callback
			'game-image-default-admin', // page
			'game_image_default_setting_section' // section
		);
	}

	public function game_image_default_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['image_0'] ) ) {
			$sanitary_values['image_0'] = sanitize_text_field( $input['image_0'] );
		}

		return $sanitary_values;
	}

	public function game_image_default_section_info() {

	}

	public function image_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="game_image_default_option_name[image_0]" id="image_0" value="%s">',
			isset( $this->game_image_default_options['image_0'] ) ? esc_attr( $this->game_image_default_options['image_0']) : ''
		);
	}

}
if ( is_admin() )
	$game_image_default = new GameImageDefault();

/*
 * Retrieve this value with:
 * $game_image_default_options = get_option( 'game_image_default_option_name' ); // Array of All Options
 * $image_0 = $game_image_default_options['image_0']; // image
 */
